# Change these first
owner: npcomplete-dev # Your GitHub organization or username, where this repository lives
repo: podcast-site-upptime # The name of this repository

sites:
  - name: NpComplete
    url: https://npcomplete.dev/
  
status-website:
  baseUrl: /podcast-site-upptime
  logoUrl: https://npcomplete.dev/wp-content/uploads/2021/01/cropped-np-32x32.png
  name: Npcomplete Upptime
  introTitle: "**NpComplete** status page."
  introMessage: This is a sample status page for [https://npcomplete.dev/](https://npcomplete.dev/)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/npcomplete-dev/podcast-site-upptime
    - title: Site
      href: https://npcomplete.dev/
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
